(* The parser functions are generated by ocamlyacc *)
let parse lexbuf =
  try Parser.expression Lexer.token lexbuf with
  | Lexer.Failure msg ->
      let pos = lexbuf.Lexing.lex_curr_p in
      Printf.eprintf "Lexing Error at line %d, char %d: %s\n"
        pos.Lexing.pos_lnum
        (pos.Lexing.pos_cnum - pos.Lexing.pos_bol)
        msg;
      exit 1
  | _ ->
      let pos = lexbuf.Lexing.lex_curr_p in
      Printf.eprintf "Parsing Error: Syntax error at line %d, char %d\n"
        pos.Lexing.pos_lnum
        (pos.Lexing.pos_cnum - pos.Lexing.pos_bol);
      exit 1

(* Read lines from standard input and parse them *)
let hello line =
  Printf.printf "> ";
  flush stdout;
  let lexbuf = Lexing.from_string line in
  let ast = parse lexbuf in
  Printf.printf "AST: %s\n" (Ast.string_of_expression ast)
